{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-1.3.0-multiplatform-sources.jar",
          "url": "collection-1.3.0-multiplatform-sources.jar",
          "size": 71076,
          "sha512": "6a46e5fca5aed0c94c1a935bae4388b2c0f60c747fd94ba2da727a00f670a460398297fd6424eb2be6689f423cdd55b88330f08a5394f0bdf01e4d777772c499",
          "sha256": "200db4b3fca99ce64de046d5a129c04c8928bc695285de9ad60c3bfc6813f07d",
          "sha1": "9c70f31e5989bb0a38d1fd69e0cdce0bdc40f687",
          "md5": "9d25940c3906cc29e8b1f94e4a6724a4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "collection-1.3.0-versionMetadata.json",
          "size": 13081,
          "sha512": "1e438f4e6d558e3dc707b4ac660ed0ee7bccc030118dcee07901839ca8952be108b7d6005242cfa061f4436d22150226a6d3683023406ce33a89a547389c6cee",
          "sha256": "fd65a0e6d72846897f7a5865ad03a1f39c7d045a0f876bff2f72b0522997ac34",
          "sha1": "b8cf2134a2e4ae1bf3d222cbd3d379c3e347e420",
          "md5": "130bb4fdb2e85e144ae0905f687d29e0"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-metadata-1.3.0.jar",
          "url": "collection-1.3.0.jar",
          "size": 15298,
          "sha512": "ff9a798d687486e64e827a0ef89d9a1584ef128ee8a4b3327e65b6c59780bfbf19333c2ce36d3e7afdcd427aecb664d7c511ebbfb7c5bbaee0e2ad1dc91c31c7",
          "sha256": "6c9df1efae8e26f9f34b2ae0294b8c2f698b8eefaac54819fdcac3973373d155",
          "sha1": "0d766b0636cdabd25a48d0c433591ce6ee980624",
          "md5": "55bed2cdd1ae70f7b3665a05ab0a831e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-kotlin-1.3.0-sources.jar",
          "url": "collection-1.3.0-sources.jar",
          "size": 49374,
          "sha512": "6902c455c014c516c1e0a333e12b64bd1c2b59495f689523cc72ad0f5b8e4c16552cd3448478bbb5e0ebc24ec78f94fbc62eb8f4401e1c289f5bd7157d5ccda5",
          "sha256": "c30371c24dd4b3a0139168daf25cce7fa428c7f692d31dc2fe1d5374934cc3ee",
          "sha1": "7f2a119cf8d23bae0b8f18f1b0ee45f99219743e",
          "md5": "0122a3cde0513ebb6505360f84f3fdc9"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosarm64/1.3.0/collection-iosarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosarm64/1.3.0/collection-iosarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosarm64/1.3.0/collection-iosarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iossimulatorarm64/1.3.0/collection-iossimulatorarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iossimulatorarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iossimulatorarm64/1.3.0/collection-iossimulatorarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iossimulatorarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iossimulatorarm64/1.3.0/collection-iossimulatorarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iossimulatorarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosx64/1.3.0/collection-iosx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iosx64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosx64/1.3.0/collection-iosx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iosx64",
        "version": "1.3.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-iosx64/1.3.0/collection-iosx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-iosx64",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../collection-jvm/1.3.0/collection-jvm-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../collection-jvm/1.3.0/collection-jvm-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../collection-jvm/1.3.0/collection-jvm-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-linuxx64/1.3.0/collection-linuxx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-linuxx64",
        "version": "1.3.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-linuxx64/1.3.0/collection-linuxx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-linuxx64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosarm64/1.3.0/collection-macosarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-macosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosarm64/1.3.0/collection-macosarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-macosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosarm64/1.3.0/collection-macosarm64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-macosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosx64/1.3.0/collection-macosx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-macosx64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosx64/1.3.0/collection-macosx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-macosx64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../collection-macosx64/1.3.0/collection-macosx64-1.3.0.module",
        "group": "androidx.collection",
        "module": "collection-macosx64",
        "version": "1.3.0"
      }
    }
  ]
}