{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt",
    "module": "coil-compose",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-compose-base",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-2.5.0.aar",
          "url": "coil-compose-2.5.0.aar",
          "size": 20609,
          "sha512": "d81905bd55280c3b20f14dff6094f80f1039004ea2161f7eb70cf43b3682204afdd86e771ef9b6f278b76f5b37e0d122c54ef621d86754ab05bae7264e43ed14",
          "sha256": "917f40475c1b206c61a489355833e111e6fde729ec0b8e3c5ccab923b283642f",
          "sha1": "f8a2b0dd3cd01cb613838b273ca129925bd20642",
          "md5": "7c38bb3c94f1db8b7dd6bd012a69eb06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-compose-base",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-2.5.0.aar",
          "url": "coil-compose-2.5.0.aar",
          "size": 20609,
          "sha512": "d81905bd55280c3b20f14dff6094f80f1039004ea2161f7eb70cf43b3682204afdd86e771ef9b6f278b76f5b37e0d122c54ef621d86754ab05bae7264e43ed14",
          "sha256": "917f40475c1b206c61a489355833e111e6fde729ec0b8e3c5ccab923b283642f",
          "sha1": "f8a2b0dd3cd01cb613838b273ca129925bd20642",
          "md5": "7c38bb3c94f1db8b7dd6bd012a69eb06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-compose-2.5.0-sources.jar",
          "url": "coil-compose-2.5.0-sources.jar",
          "size": 6603,
          "sha512": "a84cc454675c935151ea84bb0b2edff8f6dfa70e745854640b5dfea3ce589fb7369fea69a4fa0234c80ee7476856d43540d19643e70a0017eb63ad67dbc3d57e",
          "sha256": "58816bc4a01344f84cdaa8d8571b54723d640d63e731e62bc777d53b00d8ff4b",
          "sha1": "399ab6cad43ebc28b3e06a437df8928805c3b51b",
          "md5": "6956634fffb7fbe863f7b0a0086b1b22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-compose-2.5.0-javadoc.jar",
          "url": "coil-compose-2.5.0-javadoc.jar",
          "size": 288958,
          "sha512": "ac49ecda5b99a949e5baa49d76a70f7e5fc7e853f3cd88f6364a61fcc2f446dc3da1b494228ab58f19960d06c13f0b80ccef2138fa9c46b2d0fc7830d3e351a9",
          "sha256": "ffb1ab41fa8b350538ff33df2dbf5ff8906a424e89bbedc8c2cc6f7db1dffa7a",
          "sha1": "f346612b5cb0a1b7bdc981ce2006231bdf02a3ce",
          "md5": "65cfd98a3967afd4100c410148d7ca3d"
        }
      ]
    }
  ]
}
