{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt",
    "module": "coil-base",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-base-2.5.0.aar",
          "url": "coil-base-2.5.0.aar",
          "size": 437229,
          "sha512": "e1f33c1e1a4a4336cda0d8a02fc825655765115a51807607354d0598adf5d6bede47431be0e577a636aa99852eea09e17878e84b5b76e38cfca9039976c45214",
          "sha256": "bb399f8039e8cf7f159102c85b44281be2ff7ebc58214056f8601ca43fbeabc5",
          "sha1": "2781eb09c2cf68c2c0722b76a5b22f70ff1f909c",
          "md5": "c11fb8253dfb8bf467d56417bb239930"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-base-2.5.0.aar",
          "url": "coil-base-2.5.0.aar",
          "size": 437229,
          "sha512": "e1f33c1e1a4a4336cda0d8a02fc825655765115a51807607354d0598adf5d6bede47431be0e577a636aa99852eea09e17878e84b5b76e38cfca9039976c45214",
          "sha256": "bb399f8039e8cf7f159102c85b44281be2ff7ebc58214056f8601ca43fbeabc5",
          "sha1": "2781eb09c2cf68c2c0722b76a5b22f70ff1f909c",
          "md5": "c11fb8253dfb8bf467d56417bb239930"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-base-2.5.0-sources.jar",
          "url": "coil-base-2.5.0-sources.jar",
          "size": 120516,
          "sha512": "9e0a584cebf7c407dfd8d9503f2b6674366d1d130fe71eb253d736c5bf027c6a7e6407dd4e1f592009bc1ef0844c298247a21408bdfdcdc0ef8799ece8468170",
          "sha256": "7bf5b3ed02031cb9ddcbc43dc77b83752a1580f906f119a517c753caa29d5f4b",
          "sha1": "f0396d35e2bf4be253af9152f8cd7d24f39dea9b",
          "md5": "28cfbd79e16cb2a2bb6e16ec4ad9625d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-base-2.5.0-javadoc.jar",
          "url": "coil-base-2.5.0-javadoc.jar",
          "size": 681400,
          "sha512": "05d9125900aa469f9c1ea9dcbdf77253893093dbf565d101e73aaa00ec7ebfb7d4636cedb687ade0992acbea66d71196af6803f46a408193fdf6d2fd54d7758b",
          "sha256": "ce92e3f395ff98fe5d21d4bcc09686a657b93d18c700d9eb2760ae662b0c4267",
          "sha1": "fa8587ca9aeb513abd73b5e6fa67ea5573c8f1f8",
          "md5": "f0dd5aa990f9b158ab3ec8839529a155"
        }
      ]
    }
  ]
}
